config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'sextou#home'

  get '/login', to: 'spotify#new'
  get '/auth/spotify/callback', to: 'spotify#spotify'

  resources :parties, only: [:index, :new, :create]
  namespace :party do
    get '/:slug/tracks', to: 'tracks#index', as: :tracks
    post '/:slug/tracks/', to: 'tracks#create'
  end

  namespace :admin, constraints: UserIsAdmin do
    mount MissionControl::Jobs::Engine, at: "/jobs"

    resources :releases_playlists, to: 'admin/releases_playlists', only: :index
  end

  resources :friday_releases, only: [:new, :create, :destroy]
  resources :snapshot, only: [:index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friday_release.rb
class FridayRelease < ApplicationRecord
  validates :playlist_id, :user, presence: true

  belongs_to :user

  before_validation :create_playlist

  after_create :async_populate

  def create_playlist
    return unless user.present? && !playlist_id.present?

    @playlist = ::Playlist::Create.new("🔥Sextou Lançamentos🔥", user).execute

    self.playlist_id = playlist.id if playlist.id.present?
  end

  def playlist
    @playlist ||= RSpotify::Playlist.find_by_id(playlist_id)
  end

  private

  def async_populate
    UpdateFridayPlaylistJob.perform_later(user.id)
  end
end

app/models/party.rb
class Party < ApplicationRecord
  extend FriendlyId
  belongs_to :user

  friendly_id :name, use: :slugged

  def playlist
    RSpotify::Playlist.find(user.spotify_account.id, playlist_id)
  end

  def add_tracks(track_id)
    track = find_track(track_id)
    playlist.add_tracks!([track])
  end

  def find_track(track_id)
    RSpotify::Track.find(track_id)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :parties
  has_one :friday_release

  attribute :user_raw, :encrypted, type: :json, compress: true

  validates :name, :user_raw, :session_id, presence: true

  def create_playlist(name)
    spotify_account.create_playlist!(name)
  end

  def spotify_account
    RSpotify::User.new(user_raw)
  end
end

app/controllers/admin/releases_playlists_controller.rb
class Admin::ReleasesPlaylistsController < ApplicationController
  def index
    @releases = FridayRelease.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :authenticate!

  private

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logged_in?
    current_user != nil
  end

  def authenticate!
    redirect_to "/login" unless logged_in?
  end
end

app/controllers/friday_releases_controller.rb
class FridayReleasesController < ApplicationController
  before_action :authenticate!
  before_action :set_friday_release, only: :destroy

  def new
    @friday_release = FridayRelease.new
  end

  def create
    @friday_release = FridayRelease.new(user: current_user)

    if @friday_release.save
      redirect_to "/", notice: 'Friday release was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @friday_release.destroy

    redirect_to "/", notice: 'Friday release was successfully stopped.'
  end

  private

  def set_friday_release
    @friday_release = FridayRelease.find(params[:id])
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_action :authenticate!

  # GET /parties
  def index
    @parties = current_user.parties
  end

  # GET /parties/new
  def new
    @party = Party.new()
  end

  # POST /parties
  def create
    @party = Party.new(party_params)
    playlist = Playlist::Create.new(@party.name, current_user).execute

    @party.playlist_id = playlist.id
    @party.user = current_user

    if @party.save
      redirect_to @party, notice: 'Party was successfully created.'
    else
      render :new
    end
  end

  private
    def party_params
      params.require(:party).permit(:name)
    end
end

app/controllers/party/tracks_controller.rb
# frozen_string_literal: true

class Party::TracksController < ApplicationController
  before_action :set_party, only: [:index, :create]

  def index
    @party_slug = @party.slug
    @tracks = search_track_name(params[:track_name].presence)
  end

  def create
    @party.add_tracks(params[:track_id])
    redirect_to party_tracks_path
  end

  private

  def set_party
    @party = Party.friendly.find(params[:slug])
  end

  def search_track_name(track_name)
    if track_name
      RSpotify::Track.search(track_name)
    else
      []
    end
  end
end

app/controllers/sextou_controller.rb
class SextouController < ApplicationController
  before_action :authenticate!

  def home

  end
end

app/controllers/snapshot_controller.rb
class SnapshotController < ApplicationController
  before_action :authenticate!

  PER_PAGE = 25

  def index
    @playlists = current_user.spotify_account.playlists(offset: offset, limit: PER_PAGE)
    @next_page = page + 1
    @per_page = PER_PAGE
  end

  def create
    if snapshot_params.valid?
      SnapshotPlaylistJob.perform_later(current_user.id, snapshot_params.playlist_id)

      redirect_to "/", notice: 'Sua Playlist será copiada nos próximos minutos 🤙'
    else
      redirect_to snapshot_index_path, notice: 'Link inválido 🙅‍♀️'
    end
  end

  private

  def snapshot_params
    @snapshot_params ||= SnapshotParams.new(params)
  end

  def offset
    (page - 1) * PER_PAGE
  end

  def page
    (params[:page] || 1).to_i
  end
end

app/controllers/spotify_controller.rb
class SpotifyController < ApplicationController
  before_action :set_spotify_user, only: :spotify

  attr_accessor :spotify_user

  def new; end

  def spotify
    user = create_or_update

    session[:user_id] = user.id

    redirect_to "/"
  end

  private

  def user_exists?
    User.exists?(session_id: @spotify_user.id)
  end

  def create_or_update
    if user_exists?
      @current_user = User.find_by(session_id: @spotify_user.id)
      current_user.update!(user_raw: @spotify_user.to_hash)

      current_user
    else
      User.create(name: @spotify_user.display_name, user_raw: @spotify_user.to_hash, session_id: @spotify_user.id)
    end
  end

  def set_spotify_user
    @spotify_user = RSpotify::User.new(request.env['omniauth.auth'])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/releases_playlists/index.html.erb
<p id="notice"><%= notice %></p>
<h1 class="title">Friday Releasese Playlists</h1>

<ul class="list">
  <% @releases.each do |release| %>
    <li class="list__item">
      <h2 class="list__item-title"><%= "#{release.user.id}: #{release.user.spotify_account.email}" %></h2>

      <a href="<%= "https://open.spotify.com/playlist/#{release.playlist_id}" %>" class="button button--listing">Playlist</a>
    </li>
  <% end %>
</ul>

app/views/friday_releases/_form.html.erb
<%= form_with(class: 'form', model: friday_release, local: true) do |form| %>
  <% if friday_release.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friday_release.errors.count, "error") %> prohibited this friday_release from being saved:</h2>

      <ul>
        <% friday_release.errors.full_messages.each do |message| %>
          <li style="color: #000000"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form__actions">
    <%= link_to 'Voltar', parties_path, class: 'button' %>
    <%= form.submit "Criar Playlist", class: 'button form__actions-button' %>
  </div>
<% end %>

app/views/friday_releases/new.html.erb
<div class="friday-releases">
  <h1 class="title">Sextou lançamentos</h1>

  <p class="friday-releases__description">
    Eae.<br />
    Essa Playlist do sextou vai adicionar todas as músicas lançadas como albums/eps/singles durante a semana, toda sexta.<br />

    Hey o spotify já te da os lançamentos através do New Releases. E é uma ótima seleção, exatamente, ele filtra oque eles acham que vc vai querer saber.<br />

    Então pode ser que sua playlist do sextou fique gigantesca 😱.<br />
    Vai depender bastante da época e da quantidade de artista que vc segue.<br />

    Logo essa funcionalidade é para quem prefere <strong>escolher</strong> oque não quer ouvir sobre <strong>não ouvir</strong> por que não ficou sabendo.<br />
  </p>

  <%= render 'form', friday_release: @friday_release %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sextou</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>


    <link rel='stylesheet' type='text/css' href='https://fonts.googleapis.com/css?family=Marck+Script'>
    <link rel='stylesheet' type='text/css' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'></link>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="body">
    <section class="content">
      <%= yield %>
    </section>

    <%= render 'partials/footer'%>
  </body>
</html>

app/views/partials/_footer.html.erb
<% if logged_in? %>
  <div class="footer">
    <% if current_user.friday_release %>
      <%= link_to 'Parar de atualizar playlist de lançamentos', "/friday_releases/#{current_user.friday_release.id}",  method: :delete, data: { confirm: 'Are you sure?' }, class: 'button' %>
    <% else %>
      <%= link_to 'Descubra os lançamentos do artista que você segue', new_friday_release_path, class: 'button' %>
    <% end %>

    <% if current_user.admin %>
        <%= link_to 'Jobs dashboard', '/admin/jobs', class: 'button' %>
        <%= link_to 'Playlists de lançamentos', admin_releases_playlists_path, class: 'button' %>
    <% end %>
  </div>
<% end %>

app/views/parties/_form.html.erb
<%= form_with(model: party, class: "form", local: true) do |form| %>
  <% if party.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(party.errors.count, "error") %> prohibited this party from being saved:</h2>

      <ul>
        <% party.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form__field">
    <%= form.label :name %>
    <span class="form__text-input-container">
      <%= form.text_field :name %>
    </span>
  </div>

  <div class="form__actions">
    <%= link_to 'Back', parties_path, class: 'button' %>
    <%= form.submit class: 'button form__actions-button' %>
  </div>
<% end %>

app/views/parties/index.html.erb
<p id="notice"><%= notice %></p>
<h1 class="title">Parties</h1>

<% if @parties.any? %>
  <%= link_to 'Nova Party', new_party_path, class: 'button' %>

  <ul class="list">
    <% @parties.each do |party| %>
      <li class="list__item">
        <h2 class="list__item-title"><%= party.name %></h2>

        <a onClick="copyToClipboard('<%= party_tracks_url(slug: party.slug) %>')" class="button button--listing">Copiar link</a>

        <a href="<%= party_tracks_path(slug: party.slug) %>" class="button button--listing">Vamooo 🎉</a>
      </li>
    <% end %>
  </ul>
<% else %>
  <%= link_to 'Crie sua primeira pa-pa-pa-party 🎉', new_party_path, class: 'subheading' %>
<% end %>

app/views/parties/new.html.erb
<h1 class="title">New Party</h1>

<%= render 'form', party: @party %>

app/views/party/tracks/create.html.erb
<h1>Tracks#create</h1>
<p>Find me in app/views/tracks/create.html.erb</p>

app/views/party/tracks/index.html.erb
<h1 class="title">Sextou é nóis</h1>

<p class="subheading">
  <%= link_to 'parties', '/parties' %>
</p>

<div class="parties-tracks">
  <div class="parties-tracks-search__container">
    <%= form_tag(party_tracks_path(@party_slug), method: "get", class: "search-bar") do %>
    <%= text_field_tag(:track_name, nil , class: "parties-tracks-search__bar") %>
    <%= submit_tag(nil,class: 'parties-tracks-search__button')%>
    <button class="parties-tracks-search__button"></button>
    <% end %>
  </div>

  <p class="label">
    <%= @party.name %>
  </p>

  <% if @tracks.any? %>
      <ul class="list">
        <% @tracks.each do |track| %>
        <li class="list__item">
          <h2 class="list__item-title"><%= track.name %> (<%= track.artists[0].name %>)</h2>
          <%= link_to 'add to playlist', party_tracks_path(@party_slug, track_id: track.id), method: :post, class: 'button button--listing' %>
        </li>
        <% end %>
      </ul>
  <% else %>
      <h2>There are no songs with this name. :-(</h2>
  <% end %>
</div>

app/views/sextou/home.html.erb
<h1 class="title">What's up</h1>

<ul id="features" class="features">
  <li id="parties" class="features__item">
    <%= link_to parties_path do %>
      <h2 class="features__title">Parties</h2>
      <p class="features__description">Crie playlists colaborativas com quem não tem Spotify!</p>
    <% end %>
  </li>

  <li id="friday-releases" class="features__item">
    <%= link_to new_friday_release_path do %>
      <h2 class="features__title">Sextou lançamentos</h2>
      <p class="features__description">Receba o lançamentos dos seus artistas preferidos toda sexta!</p>
    <% end %>
  </li>

  <li id="snapshots" class="features__item">
    <%= link_to snapshot_index_path do %>
      <h2 class="features__title">Snapshots</h2>
      <p class="features__description">Copie aquela playlist PERFEITA do Spotify antes que eles mudem tudo!</p>
    <% end %>
  </li>
</ul>

app/views/snapshot/index.html.erb
<h1 class="title">Snapshot</h1>
<p id="notice"><%= notice %></p>

<p class="subheading">
  <%= link_to 'home', '/' %>
</p>

<% if @playlists.any? %>
  <ul class="list">
    <% if @next_page == 2 %>
      <%= form_tag(snapshot_index_path, class: "snapshots__form-list form list__item", local: true) do %>
        <div class="snapshots__form-list-item form__field">
          <%= label_tag :link %>
          <span class="form__text-input-container">
            <%= text_field_tag :link %>
          </span>
        </div>

        <div class="form__actions">
          <%= submit_tag 'snapshot!', class: 'button button--listing form__actions-button' %>
        </div>
      <% end %>
    <% end %>

    <% @playlists.each do |playlist| %>
      <li class="list__item">
        <h2 class="list__item-title"><%= playlist.name %></h2>
        <%= link_to 'selecionar', snapshot_index_path(playlist_id: playlist.id), method: :post, class: 'button button--listing' %>
      </li>
    <% end %>
  </ul>

  <% if @playlists.count == @per_page %>
    <%= link_to 'mais >', snapshot_index_path(page: @next_page), class: 'button' %>
  <% end %>
<% else %>
  <h2>You don't follow any playlist 🤔</h2>
<% end %>

app/views/spotify/add_song_form.html.erb
<%= form_tag("/playlists/add", method: "post") do %>
  <%= label_tag(:track, "song uri:") %>
  <%= text_field_tag(:track) %>
  <%= submit_tag("Add") %>
<% end %>

app/views/spotify/add_song_name.html.erb
<h1>Search</h1>
<% if @tracks.any? %>
    <ul>
      <% @tracks.each do |track| %>
      <li>
        <h2><%= track.name %> (<%= track.artists[0].name %>)</h2>
        <%= link_to 'add to playlist', "/playlists/select_song?track=#{track.id}" %>
      </li>
      <% end %>
    </ul>
<% else %>
    <h2>There are no songs with this name. :-(</h2>
<% end %>

app/views/spotify/home.html.erb
<h1 class="title">
  welcome home
</h1>

<%= link_to 'Sign in with Spotify', '/auth/spotify', class: 'button' %>

app/views/spotify/new.html.erb
<h1 class="title">
  welcome home
</h1>

<%= button_to 'Sign in with Spotify', '/auth/spotify', method: :post, class: 'button', data: { turbo: false } %>

app/views/spotify/playlists.html.erb
<h1>Playlists</h1>
<ul>
  <% @playlists.each do |playlist| %>
  <li>
    <h2><%= playlist.name %></h2>
    <%= link_to 'select playlist', "/playlists/select?playlist=#{playlist.id}" %>
  </li>
  <% end %>
</ul>

app/views/spotify/search_album.html.erb
<% if @albums.any? %>
    <% @albums.each do |album| %>
        <h2><%= album.name %></h2>
        <%= link_to 'select', "/albums?album=#{album.id}" %>
        <br/>
<% end %>
<% else %>
    <h2>There are no songs with this name.</h2>
<% end %>